
# Configuration for CyberFiles
# See https://github.com/CyberGen49/CyberFiles2#configuration for documentation

# To ensure your settings aren't wiped when updating, create a file named
# 'configUser.yml' in the same folder as this one. In that file, paste the
# options from here that you want to change.

# General settings
language: en
siteName: ''
siteDesc: "Browse and preview server files with ease."
theme: Default
hiddenFiles:
  - '*.php'
  - 'index.html'
  - '.*'
  - '_*'
hideDirWhenContains:
  - 'index.php'
  - 'index.html'
  - '_cf_hideFromList'
headerFileNameMarkdown: _cf_header.md
headerFileNameHtml: _cf_header.html
hideContentsFile: _cf_hideContents
sortTriggers:
  name: _cf_sortName
  date: _cf_sortDate
  ext: _cf_sortType
  size: _cf_sortSize
  desc: _cf_sortDesc
defaultSort:
  type: name
  desc: false
dateFormatShort: '%b %d, %Y'
dateFormatFull: '%Y/%m/%d %I:%+M %p'
upButtonInFileList: false
mobileFileListBorders: false
gridView:
  showModified: true
  showSize: false
  lines: 3
videoAutoplay: true
audioAutoplay: true
videoProgressSave:
  enable: true
  minDuration: 600 # 10 minutes
  minTime: 150 # 2m 30s
  maxTime: 150 # 2m 30s
  expire: 168 # 7 days
  prompt: true
generateThumbs: true
commands:
  #thumbImage: 'convert -define png:size=196x196  -background none "%0"  -thumbnail 196x196^ -gravity center  "%1"'
  thumbImage: 'convert -define png:size=196x196  -background none "%0"  -thumbnail 196x196^ -gravity center -extent 196x196  "%1"'
  thumbVideo: 'ffmpeg -i "%0" -ss 00:00:01.000 -vframes 1 "%1"'
textPreviewMaxSize: 1000000
shortLinkSlugLength: 8
chunkInterval: 5
logTimezone: America/Chicago
logUserIpHeader: REMOTE_ADDR